### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by renxiaohan666** [som-shahlab/clinical_trial_patient_matching#1]
Hello there, I would like to ask how your team obtained the 2018 n2c2 track1 dataset? I tried to find it on the official website, but I failed. It seems that this link https://n2c2.dbmi.hms.harvard.edu/files/n2c2_sample_file_annotations.zip does not have the dataset.

**Comment by Miking98** [comment]
Apologies for the confusion @renxiaohan666 ! Please try the link here: https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/
